### ISSUE TITLE
Unable to add sensors

### ISSUE THREAD

**Issue by llentjes** [nlrb/com.tclcode.otgw#19] opened 2019-09-26 07:31 UTC
When trying to add sensors the selection list appears (29 items, each selected) after pressing "volgende" a white screen appears and no progress is made.
I am using Homey version 2.5.2.
What can I do?

**Comment by nlrb** [comment] 2019-09-26 17:24
Suggest you report this to Athom. The app did not change and it worked before.

**Comment by llentjes** [comment] 2019-09-26 18:28
actually issue #17 (opened by jtebbens) is about the same problem.
Also is issue #15.
I believe your app is not working with homey v2. (Maybe when the app is already installed and then homey is upgraded. But it seems that a clean install on a homey v2 is not working.

**Comment by WillemHermsen** [comment] 2019-11-22 06:19
I have the same issue. Can you please fix this?
if you need any help or info please let me know!

**Comment by nlrb** [comment] 2019-11-23 15:03
Duplicate of #13 and #15.

**Closed as completed by nlrb** 2019-11-23 15:03 UTC
