### ISSUE TITLE
Homey v2.1.1, OTG v2.0.0 unable to add sensors

### ISSUE THREAD

**Issue by jtebbens** [nlrb/com.tclcode.otgw#17] opened 2019-04-13 11:21 UTC
Latest version. Just got an OTG and added it to Homey with your app.
First of all, nice work! I had some pair issues with adding it but eventually it works.
Gateway, thermostat and boiler are all fine but adding the sensors hangs during pairing. Getting the list of sensors but then after next it shows empty screen and stays there.

**Comment by nlrb** [comment] 2019-04-13 12:48
Well, the app has not changed in a long time, so it must be the FW.

**Comment by jtebbens** [comment] 2019-04-14 08:21
Yeah could be. Also noticed the boiler icons stay empty (flame, radiator, warm water tap etc). I see dotted squares.

**Comment by llentjes** [comment] 2019-09-17 12:06
I am having the same issue. What did you do to resolve this?

**Comment by nlrb** [comment] 2019-11-23 15:03
Duplicate of #13.

**Closed as completed by nlrb** 2019-11-23 15:03 UTC
